{
 "title": "API7 Gateway",
 "description": "Grafana Dashboard for API7 Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(apisix_http_status,service)"
   },
   {
    "name": "route",
    "query": "label_values(apisix_http_status,route)"
   },
   {
    "name": "instance",
    "query": "label_values(apisix_http_status,instance)"
   },
   {
    "name": "consumer",
    "query": "label_values(apisix_http_status,consumer)"
   },
   {
    "name": "node",
    "query": "label_values(apisix_http_status,node)"
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_http_requests_total{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"accepted\", instance=~\"$instance\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nginx connection state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Websocket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Websocket Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_ws_latency_bucket{node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_ws_latency_bucket{node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_ws_latency_bucket{node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Websocket Connections by worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_ws_current_connections{instance=~\"$instance\"}) by (worker)",
     "legendFormat": "Worker:{{worker}}"
    }
   ]
  },
  {
   "title": "MSG Queue Count by worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_ws_msg_queue_size{instance=~\"$instance\"}) by (worker)",
     "legendFormat": "Worker:{{worker}}"
    }
   ]
  },
  {
   "title": "Topic Count by worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_ws_topic_count{instance=~\"$instance\"}) by (worker)",
     "legendFormat": "Worker:{{worker}}"
    }
   ]
  },
  {
   "title": "Pushed MSG Count per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_ws_pub_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "MSG count"
    }
   ]
  },
  {
   "title": "Websocket Requests per second (RPS) by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_ws_status{instance=~\"$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "Status:{{status}}"
    }
   ]
  },
  {
   "title": "Received MSG Count per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_ws_received_push_total{instance=~\"$instance\"}[$__rate_interval])) by (worker)",
     "legendFormat": "Worker:{{worker}}"
    }
   ]
  },
  {
   "title": "Push Log Buffers Size by worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_ws_push_log_buffers_size{instance=~\"$instance\"}) by (worker)",
     "legendFormat": "Worker:{{worker}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Requests per second (RPS) by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (code)",
     "legendFormat": "HTTP Status:{{code}}"
    }
   ]
  },
  {
   "title": "Requests per second (RPS) per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Gateway Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Etcd modify indexes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_etcd_modify_indexes{key=~\"consumers|global_rules|max_modify_index|prev_index|protos|routes|services|ssls|stream_routes|upstreams|x_etcd_index\"}) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Etcd reachable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_etcd_reachable{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nginx metric errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_metric_errors_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nginx shared dict free space percent",
   "type": "graph",
   "description": "The free space percent of each nginx shared DICT since Gateway start",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(apisix_shared_dict_free_space_bytes * 100) / on (name) apisix_shared_dict_capacity_bytes",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}