{
 "title": "API7 Push Gateway",
 "description": "Grafana Dashboard for API7 Push Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Push", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status codes of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(status[$__rate_interval])) by (code)",
     "legendFormat": "Status:{{code}}"
    }
   ]
  },
  {
   "title": "Latency of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(connections) by (type)", "legendFormat": "Type:{{type}}" }
   ]
  },
  {
   "title": "Number of pushed messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pushed_volume[$__rate_interval])) by (worker_ip)",
     "legendFormat": "Worker:{{worker_ip}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "process cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2m])",
     "legendFormat": "totol"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "go_memstats_heap_alloc_bytes" },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "go_memstats_heap_sys_bytes" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "go_memstats_heap_idle_bytes" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "go_memstats_heap_inuse_bytes" },
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_mspan_inuse_bytes", "legendFormat": "go_memstats_mspan_inuse_bytes" },
    { "expr": "go_memstats_mspan_sys_bytes", "legendFormat": "go_memstats_mspan_sys_bytes" },
    { "expr": "go_memstats_mcache_inuse_bytes", "legendFormat": "go_memstats_mcache_inuse_bytes" },
    { "expr": "go_memstats_mcache_sys_bytes", "legendFormat": "go_memstats_mcache_sys_bytes" },
    {
     "expr": "go_memstats_buck_hash_sys_bytes",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "go_memstats_gc_sys_bytes" },
    {
     "expr": "go_memstats_other_sys_bytes - go_memstats_other_sys_bytes",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "go_memstats_next_gc_bytes" }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "totol" }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "go_memstats_stack_inuse_bytes" },
    { "expr": "go_memstats_stack_sys_bytes", "legendFormat": "go_memstats_stack_sys_bytes" }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[2m])",
     "legendFormat": "totol"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total - go_memstats_frees_total",
     "legendFormat": "totol"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "totol" }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total[2m])",
     "legendFormat": "totol"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "totol" }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[2m])",
     "legendFormat": "totol"
    }
   ]
  }
 ]
}